# Generated by Django 3.1.4 on 2021-01-02 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='RegistrationDate',
            new_name='registrationDate',
        ),
    ]
